### PR TITLE
Remove `sched` syntax from `makeCommand`.

### PR DESCRIPTION
**Pull request by jimjeffers**
The `sched` syntax is now generated in a separate component from `schedDate` and `commandText` to ensure commands are sent with only the necessary syntax to the API.

### CODE REVIEW

**Comment by jimjeffers** [comment]
@ksalamy this PR is ready to merge and release upon your review. Thanks! This closes #246 which was re-opened this week after @heavyB identified an issue attempting to run `failComponent`. Additionally, added a method to invalidate the commsQueue query so that the event shows up immediately in the adjacent sections on the sidebar.

**Comment by ksalamy** [comment]
The PR#246 fix has been merged and released to [ https://okeanids.mbari.org/dash5 | dash5 ] . 
Thanks Jim! 

Regards, 

Karen 

_______________ 
Karen A. Salamy 
Associate SW Engineer, MBARI 
P 831.775.1820 , F 831.775.1620 

	
	
Monterey Bay Aquarium Research Institute (MBARI) 
7700 Sandholdt Road, Moss Landing CA 95039 
[ http://www.mbari.org/ | www.mbari.org ] 
Advancing marine science and engineering to understand our changing ocean. 



"If we knew what it was we were doing, it would not be called research, would it?" - Albert Einstein (1879-1955) 

P Please consider the environment before printing this e-mail. 


From: "Jim Jeffers" ***@***.***> 
To: "mbari-org/dash5" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Thursday, April 13, 2023 1:37:20 PM 
Subject: [mbari-org/dash5] Remove `sched` syntax from `makeCommand`. (PR #282) 



The sched syntax is now generated in a separate component from schedDate and commandText to ensure commands are sent with only the necessary syntax to the API. 
You can view, comment on, or merge this pull request online at: 


[ https://github.com/mbari-org/dash5/pull/282 | https://github.com/mbari-org/dash5/pull/282 ] Commit Summary 


    * [ https://github.com/mbari-org/dash5/pull/282/commits/9f2203331adc2dc688b35f671e20fdb2c01bf549 | 9f22033 ] Update Map.tsx 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/a8cd1776c9bb6b9614dee4a33993fc38d5176e12 | a8cd177 ] fix #241 Incorrect runCommand=y parameter 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/1bd3d1f50e72fee703e790267cba576507e3ed0d | 1bd3d1f ] Updating Favicon to the LRAUV Dash Favicon 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/dda233da1337a163d29c8e1f846b68a19a85604b | dda233d ] Adding new LRAUV Favicon 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/455dbbf09a24d8c89909d042616a5090ff73999b | 455dbbf ] Merge branch 'mbari-org:develop' into develop 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/55d803c7b91c45b6200bd49ac538e0b2b76435c3 | 55d803c ] Merge pull request #244 from ksalamy/develop 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/bc2b6b16b38c2581029d6da7aacfef63fd377625 | bc2b6b1 ] Adding .png of LRAUV Dash Favicon 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/0c0761778721a7c4c2a2337a3a9f1f839e3abfdb | 0c07617 ] Merge branch 'develop' of https://github.com/ksalamy/dash5 into develop 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/4a3231f683bb102fe403e69e873b1963b438a6a9 | 4a3231f ] #243 - Added 'useMemo' to GMRT Layer. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/2f64e130e34960dda377909e61683593a5e715fd | 2f64e13 ] Merge pull request #245 from ksalamy/develop 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/eea6e13c602105dc120bef66b96f198ace25f46d | eea6e13 ] Updated Favicon to LRAUV favicon image. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/ba79d08a20393648ad953e112ffcaa2ecafa5e1e | ba79d08 ] Merge branch 'develop' of https://github.com/mbari-org/dash5 into develop 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/a73e5b8043eb234d98a3077bb392c46a755200c0 | a73e5b8 ] Removed req. "activeDeployment" to send commands. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/922a0aae3494be5ab0b54f6bb786facffcca6bb3 | 922a0aa ] #247 Search Broken on Command Modal - fixed 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/62251df8b19dc303941735321fb8ec3151a832c8 | 62251df ] ESRI Map Tiles Throwing 500 Errors #216 - fixed 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/f2c202c8ff4af632947391dd6a59c33350d43dd1 | f2c202c ] Added maxNativeZoom property to Maps.tsx. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/a6fd88923dbba637e8b12fd8246d48270ee9c4c0 | a6fd889 ] Added scrollWheelZoom to Map.tsx. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/3897e445b8f4bbcc24e136564b3ce35a4c454caa | 3897e44 ] Ensure initial syntax is selected by default. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/7a179d9146db780e1909592ea7bd9c93303a6806 | 7a179d9 ] Ensure `persistedCommand` is blank to trigger initial command update. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/ab814e32bfb2458349b669594793c0ac28c87080 | ab814e3 ] CommandModal stories use realistic sample data. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/70b5c17aec31fbb0940c5e5c1336eca0a7636f5f | 70b5c17 ] CommandModal test now runs through complete workflow. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/67cd6b5b5b13c9ae3e2cd1a4f3a2c5277c2bccc3 | 67cd6b5 ] Merge pull request #280 from SumoCreations/issue-246/command-not-constructed 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/f6a80442e3b4da49b3ede37b02fe390e5d1d29c8 | f6a8044 ] Temp fix on non-deployment commands. View in Comms Queue. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/411e7e9260328bd0aa6e8ac518e9da7f5a732ec6 | 411e7e9 ] Temp fix on non-deployment commands. View in Comms Queue. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/60b96c90987fed4eada71e5792b1ccf326644fd2 | 60b96c9 ] Mission & Command time default set to 'ASAP'. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/b716fc3f415d9e523c2038f630ca47ef6b6b00e4 | b716fc3 ] Set VehicleAccordion to not open on Schedule tab but closed. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/c2a898b357f3b4ca0ef0146fa22e2b3823306c90 | c2a898b ] Updated index === 0 vehicle status statement. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/e555833b5a5a91076476ce703c8fe9e44747c8b1 | e555833 ] Added ScaleControl View to the Map Views. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/4d515370360b41ecd44263dc41444e1d85226246 | 4d51537 ] Adding Mouse Coordinates to Maps. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/6b8d3dbb3477ff66095575d2e87d36c5485e5165 | 6b8d3db ] useCreateCommand invalidated events cache. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/e546cd60a5dd88413944d950aea33bf190b259c4 | e546cd6 ] Refactored `makeCommand` method to exclude sched syntax. 
    * [ https://github.com/mbari-org/dash5/pull/282/commits/d06820d97e56fb817048b810a39256d778ceca9e | d06820d ] Updated yarn resolutions. 
File Changes 


( [ https://github.com/mbari-org/dash5/pull/282/files | 27 files ] ) 

    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-a4ad53b82520115e10558576da74f8bb498ee17d46027860bcac91b17feabec8 | apps/lrauv-dash2/components/CommandModal.tsx ] (11) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-f6df1cfea36b2af405c9f579affa88569149768b398336acc5feec509baceebb | apps/lrauv-dash2/components/CommsSection.tsx ] (4) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-1db52f29e415191285c0f1cf38f01d733a5816c43f6c18abb7ab7de4b47a2f53 | apps/lrauv-dash2/components/MissionModal.tsx ] (8) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-8ff8f97cc6f320566cce8c8d3f5ed97bbf53a262025ddf1b9a07e5e41dfc4df0 | apps/lrauv-dash2/components/ScheduleSection.tsx ] (8) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-5dd539cca4624d06e5bdfe9e2b5624e419e52ce7639ee686c0cf489c2a3445cd | apps/lrauv-dash2/components/VehicleAccordion.tsx ] (27) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-0ca95d39e11cbeb733596b1f99c3e2699b05a3fb40af6c1230221b4ca33bf27c | apps/lrauv-dash2/lib/makeCommand.test.ts ] (22) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-670c845402847e7e336e188b9440a4c9c2dd90b963e5a3f6e9a6b49daaccaac9 | apps/lrauv-dash2/lib/makeCommand.ts ] (27) 
    * A [ https://github.com/mbari-org/dash5/pull/282/files#diff-c07d677e2dca8192c2596a50e7be4e9855e525d974be9d79ea938fe6200c4254 | apps/lrauv-dash2/lrauv-logo-w28.png ] (0) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-6fecd94ec5c19108c50a72b6b1f6977e8809abb6e530efeec6b64558acf0eb9e | apps/lrauv-dash2/package.json ] (7) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-ed40c9fdb95fd8c8c90f11af0b8b41c5a39db6bd69aeda165dfb2ccc8389dc7e | apps/lrauv-dash2/pages/_document.tsx ] (2) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-fd1b3d180df6f9b6d0f758d1e23ffdad6d6a66d5b3bbc9173869383e116838c6 | apps/lrauv-dash2/public/favicon.ico ] (0) 
    * A [ https://github.com/mbari-org/dash5/pull/282/files#diff-b6179483649b4fac5304576ee3e6ff0581074a7b9265fa8eba60d699bbe18c1a | apps/lrauv-dash2/public/lrauv-logo-w28.png ] (0) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 | package.json ] (1) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-eca2a971e854dd6519543ea6bd157bab7cf5bb8cbf9402a42229c15731e7afa4 | packages/api-client/src/react-query/Command/useCreateCommand.ts ] (25) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-88d77dddb27a160ba5cc1bc8ca24012f8613052459094a94144062113d3b71a2 | packages/react-ui/package.json ] (12) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-fce2262717968b1daa54fec0aaf0b2ff37f31556ba044858df8d5ffec56f9d97 | packages/react-ui/src/Map/Map.tsx ] (79) 
    * A [ https://github.com/mbari-org/dash5/pull/282/files#diff-f5c5e5344afff98192f0e6fc11b7b29897fdbf89082fc1250bb15b53cae0c2f9 | packages/react-ui/src/Map/MouseCoordinates.tsx ] (121) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-6057ed23cb472f4b079baf6c287032d081e9490c42d70afef81b7a0174581b04 | packages/react-ui/src/Map/useMapBaseLayer.ts ] (4) 
    * A [ https://github.com/mbari-org/dash5/pull/282/files#diff-97c12ee548a9b3e8c747b2be350600174c67048d2dfe328cccefb03aa4c18cd3 | packages/react-ui/src/Modals/CommandModal.sampleProps.tsx ] (139) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-c1f6dc548f4f295194011283ab6bba0db4365f8014216326224c4ee98fc282f0 | packages/react-ui/src/Modals/CommandModal.stories.tsx ] (79) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-8205f44ea43bc2cc76bba772fe1045031e7f7a56fef8cd13532abcabe7dd1e80 | packages/react-ui/src/Modals/CommandModal.test.tsx ] (81) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-f9deabf0611a4945997f40503dec55b2ca45a5370ca21f8f3c24ac13f133b564 | packages/react-ui/src/Modals/CommandModal.tsx ] (6) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-ed0e721fc560e289279e54067ffbeb4d3a246cea072d14ea1583f71a721b0c0a | packages/react-ui/src/Modals/CommandModalSteps/BuildTemplatedCommandStep.tsx ] (3) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-a1bb60b974590e7c4a4eb961576b6093ac1c79cbaef21df107cbe945a106def4 | packages/react-ui/src/Modals/CommandModalSteps/SelectCommandStep.tsx ] (8) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-2c6965d4ba2efc469f8b9234079c00b5e0b9087468b2b6677cacd030da563f7d | packages/react-ui/src/Modals/MissionModal.tsx ] (2) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-f8de965273949793edc0fbfe249bb458c0becde39b2e141db087bcbf5d4ad5e3 | turbo.json ] (8) 
    * M [ https://github.com/mbari-org/dash5/pull/282/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de | yarn.lock ] (139) 
Patch Links: 


    * [ https://github.com/mbari-org/dash5/pull/282.patch | https://github.com/mbari-org/dash5/pull/282.patch ] 
    * [ https://github.com/mbari-org/dash5/pull/282.diff | https://github.com/mbari-org/dash5/pull/282.diff ]

**Comment by jimjeffers** [comment]
@ksalamy I corrected the merge conflicts that were preventing you from merging this PR which should resolve #246

**Comment by ksalamy** [comment]
Hi Jim,  Apologies if I missed this. Thanks for checking into it again. I 'believe' this is now closed as the merge states it has been committed with 7bb6c28 into mbari-org:develop.  Please let me know if there are other issues.

**Pull request merged**
